# Generated by Django 3.1 on 2020-10-30 10:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_authposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthPosts',
            new_name='AssignCourses',
        ),
    ]
