# Generated by Django 3.1 on 2020-11-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201030_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigncourses',
            name='user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
