# Generated by Django 3.1.3 on 2020-11-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201109_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_mark', models.CharField(max_length=100)),
                ('Second_mark', models.CharField(max_length=100)),
                ('Third_mark', models.CharField(max_length=100)),
                ('fourth_mark', models.CharField(max_length=100)),
                ('fifth_mark', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
