# Generated by Django 3.1.3 on 2020-11-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201116_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='response',
            name='rightans',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
