# Generated by Django 3.1.3 on 2020-11-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201116_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='rightans',
            field=models.CharField(default='', max_length=100),
        ),
    ]
