# Generated by Django 3.1.3 on 2020-11-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201116_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='course',
            new_name='quiz',
        ),
    ]
